name: deploy-react

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t react-frontend .

      - name: Save Docker image as archive
        run: docker save react-frontend -o react-frontend.tar

      - name: Copy image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./react-frontend.tar"
          target: "/home/${{ secrets.SERVER_USER }}/react-frontend.tar"

      - name: Run container on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Удаляем старый контейнер, если он существует
            docker stop react-frontend || true
            docker rm react-frontend || true

            docker load -i /home/${{ secrets.SERVER_USER }}/react-frontend.tar/react-frontend.tar

            docker run -d --name react-frontend -p 3000:3000 --restart=unless-stopped react-frontend
